### PR TITLE
Remove survey alias pages

### PR DESCRIPTION
**Pull request by lassik**
The corresponding surveys are no longer in this repo.

### CODE REVIEW

**Comment by johnwcowan** [comment]
Say where they are.

**Comment by lassik** [comment]
We moved them to https://github.com/schemedoc/surveys and https://doc.scheme.org/surveys/ a couple weeks ago.

**Comment by johnwcowan** [comment]
Yes, I know.  But saying "These pages are not in this survey" should be
extended to say where they are.

**Comment by lassik** [comment]
OK, commit message extended.

**Pull request merged**
